export const defaultName = 'ExMachina';
export const anagramWin = 5;
export const githubUrl = 'https://github.com/tyler-pepper/codesamples';
export const drupalUrl = 'https://www.drupal.org/u/tyler-the-creator';
export const anagrams = {
  best: 'anaemic',
  all: [
    'anaemic',
    'machine',
    'maniac',
    'anemia',
    'anemic',
    'cinema',
    'mania',
    'chain',
    'china',
    'manic',
    'chime',
    'niche',
    'mince',
    'ache',
    'each',
    'acme',
    'came',
    'mace',
    'acne',
    'cane',
    'mica',
    'ahem',
    'amen',
    'mane',
    'mean',
    'name',
    'exam',
    'main',
    'mice',
    'nice',
    'chin',
    'inch',
    'mien',
    'mine',
    'minx',
    'aha',
    'ace',
    'cam',
    'can',
    'axe',
    'ham',
    'aim',
    'ani',
    'man',
    'ice',
    'chi',
    'hie',
    'hem',
    'hen',
    'hex',
    'men',
    'him',
    'mix',
    'nix',
  ]
};

export default {
  defaultName,
  anagramWin,
  githubUrl,
  drupalUrl,
  anagrams,
};
